#!/bin/sh

# Set these paths appropriately

BIN="/mnt/c/Users/fabien/Documents/marsouinProject/bin"
CMD="/mnt/c/Users/fabien/Documents/marsouinProject/cmd"
LIB="/mnt/c/Users/fabien/Documents/marsouinProject/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
