#!/bin/sh

# Set these paths appropriately

BIN="/mnt/c/Users/fabien/Documents/marsouinProject/bin"
CMD="/mnt/c/Users/fabien/Documents/marsouinProject/cmd"
LIB="/mnt/c/Users/fabien/Documents/marsouinProject/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek-utf8.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

