#!/bin/sh

# Set these paths appropriately

BIN="/mnt/c/Users/fabien/Documents/marsouinProject/bin"
CMD="/mnt/c/Users/fabien/Documents/marsouinProject/cmd"
LIB="/mnt/c/Users/fabien/Documents/marsouinProject/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/czech-abbreviations-utf8
PARFILE=${LIB}/czech-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
